#!/bin/bash
# Code here will be executed on every boot and shutdown.
  
case "$1" in
    start)
        # Code in here will only be executed on boot.
        echo "export PATH=/userdata/system/pixelcade/jdk/bin:\$PATH" > /etc/profile.d/pixelcade_path.sh
        chmod +x /etc/profile.d/pixelcade_path.sh
        # set the java path, DOFLinx needs it
        export PATH=/userdata/system/pixelcade/jdk/bin:$PATH
        # Re-create the plugin symblink in case it got blown away
        if [ ! -L "/usr/bin/mame/plugins/doflinx" ]; then
            ln -sf /userdata/saves/mame/plugins/doflinx /usr/bin/mame/plugins/doflinx
        fi
        sleep 5
        # Note if sleep 1 is not there, then sometimes DOFLinx will crash on boot
        cd /userdata/system/doflinx && ./DOFLinx PATH_INI=/userdata/system/doflinx/config/DOFLinx.ini &
        ;;
    stop)
        # Code in here will only be executed on shutdown.
        ;;
    restart|reload)
        # Code in here will executed (when?).
        ;;
    *)
        # Code in here will be executed in all other conditions.
        ;;
esac
 
exit $?